//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminDayAndNight.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class blocking_user
    {
        public int sloppy_user { get; set; }
        public System.DateTime date_block { get; set; }
        public Nullable<int> count_block { get; set; }
    
        public virtual user user { get; set; }
    }
}
