//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminDayAndNight.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class blocking
    {
        public int id { get; set; }
        public System.DateTime block_time { get; set; }
        public int block_user { get; set; }
    
        public virtual user user { get; set; }
    }
}
