//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminDayAndNight.BD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class group363_06Entities : DbContext
    {
        public group363_06Entities()
            : base("name=group363_06Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<booking_history> booking_history { get; set; }
        public virtual DbSet<borrow_room> borrow_room { get; set; }
        public virtual DbSet<client> client { get; set; }
        public virtual DbSet<info_room> info_room { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<status_User> status_User { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<type_room> type_room { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
